name: CI

on: [push, pull_request]

jobs:
  test:
    strategy:
      matrix:
        operating-system: [ubuntu-latest]
        ocaml-version: [4.10.0, 4.11.0]
    runs-on: ${{ matrix.operating-system }}
    steps:
    - uses: actions/checkout@v2
    - uses: actions-ml/setup-ocaml@master
      with:
        ocaml-version: ${{ matrix.ocaml-version }}
    - name: Add mirage-dev repository
      run: opam repo add mirage-dev git+https://github.com/TheLortex/mirage-dev#mirage-4
    - name: External dependencies
      run: opam depext -yt ocaml-freestanding solo5-bindings-spt
    - name: Install ocaml-freestanding, bindings, dune and opam-monorepo
      run: opam install -t -y ocaml-freestanding solo5-bindings-spt dune opam-monorepo
    - name: Run opam-monorepo
      run: 
        - opam monorepo lock
        - opam monorepo pull
    - name: Compiling example project
      run: opam exec -- dune build --workspace dune-workspace.freestanding
    - name: Running tests
      run: opam exec -- dune runtest --workspace dune-workspace.freestanding
